### ISSUE TITLE
GoldenHopperBlockEntity is duplicating behavior that vanilla interfaces provide

### ISSUE THREAD

**Issue by 2No2Name** [haykam821/Golden-Hoppers#1]
GoldenHopperBlockEntity seems to be incompatible with my hopper optimizations mod (see https://github.com/2No2Name/hopperOptimizations/issues/23 ).
I think it would be best to make GoldenHopperBlockEntity use vanilla's SidedInventory::canInsert (refer to the shulker box not accepting shulker boxes code to see how it can work) to define which items can be inserted into the slots of the Golden Hopper.
I will work on making hopper optimizations compatible with a HopperBlockEntity subclass that implements SidedInventory::canInsert, which should in total, fix the compatibility issues.

**Comment by 2No2Name** [comment]
Thank you, I also changed it in hopper optimizations now. A minor problem when testing that i noticed is that the hopper does not realize that the filter item is being changed. If you call BlockEntity::resetBlock (This clears some cached data in my mod.) when changing the filter item that would be fixed too, but I think that is only a minor problem anyways.

**Comment by haykam821** [comment]
Wouldn't the same problem happen with `/data block modify`, which also only uses `markDirty`?

**Comment by 2No2Name** [comment]
Yes it probably will, so I might have to hook into markDirty as well. Thanks
