### ISSUE TITLE
Missing texture?

### ISSUE THREAD

**Issue by Laifsyn** [haykam821/Golden-Hoppers#17]
![image](https://user-images.githubusercontent.com/99366187/173986126-f51d5c1c-dd08-4dbe-b346-2a2cda5b7cf2.png)

**Comment by haykam821** [comment]
It looks like data generation didn't run during the build process.

**Comment by haykam821** [comment]
[Version 1.3.3](https://github.com/haykam821/Golden-Hoppers/releases/tag/1.3.3) should include generated data.
