### ISSUE TITLE
Filter Removed

### ISSUE THREAD

**Issue by ronc617** [haykam821/Golden-Hoppers#8]
The Item that is in the golden hopper filter slot is removed when you 
log out of Single player. 1.18 Fabric

Hoppers need to be setup every time that you log into the game

**Comment by haykam821** [comment]
It looks like the version of Golden Hoppers compatible with 1.17 silently breaks in 1.18. This is because a method signature changed, meaning the filter serialization is never called. Fortunately, 44af0d34f0af8cd6e268767afa478e514caa6a6e already fixes this.

**Comment by haykam821** [comment]
Version 1.2.0 has been released, which properly supports Minecraft 1.18.
